-- =============================================================================
-- classifier.vhd  —  Classifier head for MNIST ViT
-- =============================================================================
-- Input:  streaming encoder output  (SEQ_LEN × D_MODEL int8 tokens)
-- Output: predicted digit class  0–9
--
-- Pipeline:
--   1. GAP: sum all SEQ_LEN token vectors element-wise, then >>LOG_SL
--   2. Linear: W(10×32) @ gap + b → 10 logits  (Q1.7 GEMM, >>7 + sat8)
--   3. Argmax over 10 logits → predicted class
--
-- Weights from weights_pkg constants (auto-generated by export_qat).
-- =============================================================================

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.clog2_pkg.all;
use work.weights_pkg.all;

entity classifier is
    generic (
        DATA_WIDTH : positive := 8;
        D_MODEL    : positive := 32;
        SEQ_LEN    : positive := 16;
        N_CLS      : positive := 10
    );
    port (
        clk  : in  std_logic;
        rstn : in  std_logic;

        -- Control
        start : in  std_logic;
        done  : out std_logic;

        -- Streaming encoder output (SEQ_LEN × D_MODEL tokens)
        i_data    : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
        i_valid   : in  std_logic;
        i_last    : in  std_logic;
        i_channel : in  integer;

        -- Predicted class (valid when done = '1')
        o_class : out integer range 0 to N_CLS - 1
    );
end entity classifier;

architecture rtl of classifier is

    -- -------------------------------------------------------------------------
    -- Constants
    -- -------------------------------------------------------------------------
    constant LOG_SL : positive := clog2(SEQ_LEN);          -- log2(16) = 4
    constant I8_MAX : integer  := 2 ** (DATA_WIDTH - 1) - 1;
    constant I8_MIN : integer  := -(2 ** (DATA_WIDTH - 1));

    -- GAP accumulator: SEQ_LEN=16 × max|127| → 12-bit (with sign)
    constant GAP_W  : positive := DATA_WIDTH + LOG_SL;       -- 12

    -- Linear accumulator: K=32 × 127² = 515168 → needs 20-bit + sign
    constant LIN_W  : positive := 24;

    -- -------------------------------------------------------------------------
    -- Types
    -- -------------------------------------------------------------------------
    type gap_buf_t  is array (0 to D_MODEL - 1) of signed(GAP_W - 1 downto 0);
    type gap_out_t  is array (0 to D_MODEL - 1) of signed(DATA_WIDTH - 1 downto 0);
    type lin_buf_t  is array (0 to N_CLS - 1)  of signed(LIN_W - 1 downto 0);

    -- -------------------------------------------------------------------------
    -- Weight ROMs (distributed LUTRAM, async read)
    -- -------------------------------------------------------------------------
    constant cw_rom : classifier_w_rom_t := CLASSIFIER_W_ROM;
    constant cb_rom : classifier_b_rom_t := CLASSIFIER_B_ROM;
    attribute rom_style : string;
    attribute rom_style of cw_rom : constant is "distributed";
    attribute rom_style of cb_rom : constant is "distributed";

    -- -------------------------------------------------------------------------
    -- Data-path signals
    -- -------------------------------------------------------------------------
    signal gap_acc  : gap_buf_t;
    signal gap_out  : gap_out_t;
    signal lin_acc  : lin_buf_t;

    -- -------------------------------------------------------------------------
    -- FSM
    -- -------------------------------------------------------------------------
    type state_t is (
        ST_IDLE,
        ST_GAP_ACC,     -- accumulate SEQ_LEN token vectors
        ST_GAP_SHIFT,   -- right-shift by LOG_SL
        ST_LIN_INIT,    -- load bias into lin_acc, pre-shifted by DATA_WIDTH-1
        ST_LIN_MAC,     -- W @ gap_out inner-product
        ST_ARGMAX,      -- find argmax over N_CLS logits
        ST_DONE
    );
    signal state : state_t := ST_IDLE;

    signal d_cnt    : integer range 0 to D_MODEL := 0;
    signal cls_cnt  : integer range 0 to N_CLS   := 0;
    signal k_cnt    : integer range 0 to D_MODEL := 0;
    signal gap_idx  : integer range 0 to D_MODEL - 1 := 0;
    signal element_cnt : integer range 0 to SEQ_LEN * D_MODEL := 0;

    signal best_cls : integer range 0 to N_CLS - 1 := 0;
    signal best_val : signed(DATA_WIDTH - 1 downto 0);

    -- -------------------------------------------------------------------------
    -- Helper: sat8 returning signed
    -- -------------------------------------------------------------------------
    function sat8s (x : signed) return signed is
    begin
        if x > to_signed(I8_MAX, x'length) then
            return to_signed(I8_MAX, DATA_WIDTH);
        elsif x < to_signed(I8_MIN, x'length) then
            return to_signed(I8_MIN, DATA_WIDTH);
        end if;
        return resize(x, DATA_WIDTH);
    end function;

begin

    p_main : process(clk) is
        variable v_tok  : signed(DATA_WIDTH - 1 downto 0);
        variable v_cw   : signed(DATA_WIDTH - 1 downto 0);
        variable v_prod : signed(2 * DATA_WIDTH - 1 downto 0);
        variable v_log  : signed(DATA_WIDTH - 1 downto 0);
    begin
        if rising_edge(clk) then
            if rstn = '0' then
                state    <= ST_IDLE;
                d_cnt    <= 0;
                cls_cnt  <= 0;
                k_cnt    <= 0;
                gap_idx  <= 0;
                element_cnt <= 0;
                best_cls <= 0;
                best_val <= to_signed(I8_MIN, DATA_WIDTH);
                done     <= '0';
                o_class  <= 0;
                for i in 0 to D_MODEL - 1 loop
                    gap_acc(i) <= (others => '0');
                    gap_out(i) <= (others => '0');
                end loop;
                for i in 0 to N_CLS - 1 loop
                    lin_acc(i) <= (others => '0');
                end loop;
            else
                done <= '0';

                case state is

                    -- ---------------------------------------------------------
                    when ST_IDLE =>
                        for i in 0 to D_MODEL - 1 loop
                            gap_acc(i) <= (others => '0');
                        end loop;
                        d_cnt   <= 0;
                        cls_cnt <= 0;
                        k_cnt   <= 0;
                        gap_idx <= 0;
                        element_cnt <= 0;
                        if start = '1' then
                            state <= ST_GAP_ACC;
                        end if;

                    -- ---------------------------------------------------------
                    -- Global-average-pool accumulation
                    -- ---------------------------------------------------------
                    when ST_GAP_ACC =>
                        if i_valid = '1' then
                            v_tok := signed(i_data);
                            gap_acc(gap_idx) <=
                                gap_acc(gap_idx)
                                + resize(v_tok, GAP_W);
                            
                            -- Cyclically increment feature index
                            if gap_idx = D_MODEL - 1 then
                                gap_idx <= 0;
                            else
                                gap_idx <= gap_idx + 1;
                            end if;

                            -- Ingest exactly SEQ_LEN * D_MODEL elements before shifting
                            if element_cnt = SEQ_LEN * D_MODEL - 1 then
                                element_cnt <= 0;
                                d_cnt <= 0;
                                state <= ST_GAP_SHIFT;
                            else
                                element_cnt <= element_cnt + 1;
                            end if;
                        end if;

                    -- ---------------------------------------------------------
                    -- Divide by SEQ_LEN = 2^LOG_SL  (one element per cycle)
                    -- ---------------------------------------------------------
                    when ST_GAP_SHIFT =>
                        gap_out(d_cnt) <=
                            sat8s(shift_right(gap_acc(d_cnt), LOG_SL));
                        if d_cnt = D_MODEL - 1 then
                            cls_cnt <= 0;
                            state   <= ST_LIN_INIT;
                        else
                            d_cnt <= d_cnt + 1;
                        end if;

                    -- ---------------------------------------------------------
                    -- Load bias (pre-shifted <<7) into lin_acc  (N_CLS cycles)
                    -- ---------------------------------------------------------
                    when ST_LIN_INIT =>
                        lin_acc(cls_cnt) <= shift_left(
                            resize(signed(cb_rom(cls_cnt)), LIN_W),
                            DATA_WIDTH - 1);
                        if cls_cnt = N_CLS - 1 then
                            cls_cnt <= 0;
                            k_cnt   <= 0;
                            state   <= ST_LIN_MAC;
                        else
                            cls_cnt <= cls_cnt + 1;
                        end if;

                    -- ---------------------------------------------------------
                    -- Linear MAC: lin_acc[c] += W[c,k] * gap_out[k]
                    -- Both cw_rom and gap_out are async-readable (no latency).
                    -- Inner loop k = 0..D_MODEL-1, outer cls_cnt = 0..N_CLS-1.
                    -- ---------------------------------------------------------
                    when ST_LIN_MAC =>
                        v_cw   := signed(cw_rom(cls_cnt * D_MODEL + k_cnt));
                        v_prod := gap_out(k_cnt) * v_cw;
                        lin_acc(cls_cnt) <=
                            lin_acc(cls_cnt) + resize(v_prod, LIN_W);

                        if k_cnt = D_MODEL - 1 then
                            k_cnt <= 0;
                            if cls_cnt = N_CLS - 1 then
                                cls_cnt  <= 0;
                                best_cls <= 0;
                                best_val <= to_signed(I8_MIN, DATA_WIDTH);
                                state    <= ST_ARGMAX;
                            else
                                cls_cnt <= cls_cnt + 1;
                            end if;
                        else
                            k_cnt <= k_cnt + 1;
                        end if;

                    -- ---------------------------------------------------------
                    -- Argmax over N_CLS logits
                    -- ---------------------------------------------------------
                    when ST_ARGMAX =>
                        v_log := sat8s(
                            shift_right(lin_acc(cls_cnt), DATA_WIDTH - 1));
                        if v_log > best_val then
                            best_val <= v_log;
                            best_cls <= cls_cnt;
                        end if;
                        if cls_cnt = N_CLS - 1 then
                            state <= ST_DONE;
                        else
                            cls_cnt <= cls_cnt + 1;
                        end if;

                    -- ---------------------------------------------------------
                    when ST_DONE =>
                        o_class <= best_cls;
                        done    <= '1';
                        state   <= ST_IDLE;

                end case;
            end if;
        end if;
    end process p_main;

end architecture rtl;
