-- ============================================================================
-- frontend_mem.vhd  —  BRAM-ROM weight memories for patch_embed + classifier
-- ============================================================================
-- All five frontend weight arrays are stored as BRAM ROMs whose initial
-- contents come from weights_pkg.vhd (auto-generated by: python mnist_poc.py
-- export_qat).
--
-- BRAM inference pattern (same as weight_mem.vhd):
--   1. Signal initialised from package constant  (never written at runtime)
--   2. Read address registered on rising clock edge
--   3. Data output combinational from registered address
--   4. rom_style = "block" attribute forces BRAM mapping
--
-- Read timing:
--   Cycle N  : rd_addr presented
--   Cycle N+1: rd_data valid
-- ============================================================================

library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;

use work.clog2_pkg.all;
use work.weights_pkg.all;

entity frontend_mem is
    generic (
        DATA_WIDTH  : positive := 8;
        PATCH_SIZE  : positive := 7;    -- pixels per patch side
        D_MODEL     : positive := 32;
        SEQ_LEN     : positive := 16;
        N_CLS       : positive := 10
    );
    port (
        clk : in std_logic;

        -- Patch-projection weight: (D_MODEL × PATCH_SIZE²)
        pw_addr  : in  std_logic_vector(clog2(D_MODEL * PATCH_SIZE * PATCH_SIZE) - 1 downto 0);
        pw_re    : in  std_logic;
        pw_data  : out std_logic_vector(DATA_WIDTH - 1 downto 0);

        -- Patch-projection bias: (D_MODEL)
        pb_addr  : in  std_logic_vector(clog2(D_MODEL) - 1 downto 0);
        pb_re    : in  std_logic;
        pb_data  : out std_logic_vector(DATA_WIDTH - 1 downto 0);

        -- Positional embedding: (SEQ_LEN × D_MODEL)
        pe_addr  : in  std_logic_vector(clog2(SEQ_LEN * D_MODEL) - 1 downto 0);
        pe_re    : in  std_logic;
        pe_data  : out std_logic_vector(DATA_WIDTH - 1 downto 0);

        -- Classifier weight: (N_CLS × D_MODEL)
        cw_addr  : in  std_logic_vector(clog2(N_CLS * D_MODEL) - 1 downto 0);
        cw_re    : in  std_logic;
        cw_data  : out std_logic_vector(DATA_WIDTH - 1 downto 0);

        -- Classifier bias: (N_CLS)
        cb_addr  : in  std_logic_vector(clog2(N_CLS) - 1 downto 0);
        cb_re    : in  std_logic;
        cb_data  : out std_logic_vector(DATA_WIDTH - 1 downto 0)
    );
end entity frontend_mem;

architecture rtl of frontend_mem is

    ---------------------------------------------------------------------------
    -- ROM signals initialised from weights_pkg constants
    ---------------------------------------------------------------------------
    signal pw_mem : patch_proj_w_rom_t := PATCH_PROJ_W_ROM;
    signal pb_mem : patch_proj_b_rom_t := PATCH_PROJ_B_ROM;
    signal pe_mem : pos_embed_rom_t    := POS_EMBED_ROM;
    signal cw_mem : classifier_w_rom_t := CLASSIFIER_W_ROM;
    signal cb_mem : classifier_b_rom_t := CLASSIFIER_B_ROM;

    attribute rom_style : string;
    attribute rom_style of pw_mem : signal is "block";
    attribute rom_style of pb_mem : signal is "block";
    attribute rom_style of pe_mem : signal is "block";
    attribute rom_style of cw_mem : signal is "block";
    attribute rom_style of cb_mem : signal is "block";

    ---------------------------------------------------------------------------
    -- Registered read addresses  (BRAM registered-address read pattern)
    ---------------------------------------------------------------------------
    signal pw_addr_r : integer range 0 to D_MODEL * PATCH_SIZE * PATCH_SIZE - 1 := 0;
    signal pb_addr_r : integer range 0 to D_MODEL - 1 := 0;
    signal pe_addr_r : integer range 0 to SEQ_LEN * D_MODEL - 1 := 0;
    signal cw_addr_r : integer range 0 to N_CLS * D_MODEL - 1 := 0;
    signal cb_addr_r : integer range 0 to N_CLS - 1 := 0;

begin

    ---------------------------------------------------------------------------
    -- Synchronous address registration
    ---------------------------------------------------------------------------
    p_addr : process (clk) is
    begin
        if rising_edge(clk) then
            pw_addr_r <= to_integer(unsigned(pw_addr));
            pb_addr_r <= to_integer(unsigned(pb_addr));
            pe_addr_r <= to_integer(unsigned(pe_addr));
            cw_addr_r <= to_integer(unsigned(cw_addr));
            cb_addr_r <= to_integer(unsigned(cb_addr));
        end if;
    end process p_addr;

    ---------------------------------------------------------------------------
    -- Combinational ROM read from registered address
    ---------------------------------------------------------------------------
    pw_data <= pw_mem(pw_addr_r);
    pb_data <= pb_mem(pb_addr_r);
    pe_data <= pe_mem(pe_addr_r);
    cw_data <= cw_mem(cw_addr_r);
    cb_data <= cb_mem(cb_addr_r);

end architecture rtl;
