-- =============================================================================
-- patch_embed.vhd  —  Patch embedding for 28×28 MNIST ViT
-- =============================================================================
-- Divides a 28×28 image into 4×4 = 16 non-overlapping 7×7 patches, projects
-- each 49-pixel patch to D_MODEL=32 dimensions, adds positional embedding.
-- All weights come from weights_pkg (auto-generated by export_qat).
--
-- Operation per patch p (0..15):
--   proj[d] = sat8( (sum_{k=0}^{48} W[d,k] * pix[p,k]  +  b[d]<<7) >> 7 )
--   out[p,d] = sat8( proj[d] + pos_embed[p,d] )
--
-- Weight storage: initialized from weights_pkg constants as local arrays.
-- Pixel buffer:   784 × 8-bit FF array (async read, sync write).
-- Both pixel and weight reads are combinational → no pipeline latency in MAC.
--
-- Resource estimate (DATA_WIDTH=8, D_MODEL=32, PATCH_SIZE=7, SEQ_LEN=16):
--   pixel_buf  : 6272 FFs (~15 % of Artix-7 FFs)
--   pw_rom     : ~200 LUTs (distributed)
--   pb/pe roms : ~70  LUTs (distributed)
--   FSM logic  : ~100 LUTs
-- =============================================================================

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.clog2_pkg.all;
use work.weights_pkg.all;

entity patch_embed is
    generic (
        DATA_WIDTH  : positive := 8;
        PATCH_SIZE  : positive := 7;
        IMG_SIZE    : positive := 28;
        D_MODEL     : positive := 32;
        SEQ_LEN     : positive := 16
    );
    port (
        clk  : in  std_logic;
        rstn : in  std_logic;

        -- Control
        start : in  std_logic;
        done  : out std_logic;

        -- Streaming pixel input (784 values, raster-scan, Q1.7 int8)
        i_data  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
        i_valid : in  std_logic;

        -- Streaming token output (SEQ_LEN × D_MODEL, row-major)
        o_data    : out std_logic_vector(DATA_WIDTH - 1 downto 0);
        o_valid   : out std_logic;
        o_last    : out std_logic;
        o_channel : out integer
    );
end entity patch_embed;

architecture rtl of patch_embed is

    -- -------------------------------------------------------------------------
    -- Derived constants
    -- -------------------------------------------------------------------------
    constant PATCH_PX    : positive := PATCH_SIZE * PATCH_SIZE;     -- 49
    constant N_PX        : positive := IMG_SIZE * IMG_SIZE;          -- 784
    constant PATCHES_SID : positive := IMG_SIZE / PATCH_SIZE;        -- 4
    constant I8_MAX      : integer  := 2 ** (DATA_WIDTH - 1) - 1;   -- 127
    constant I8_MIN      : integer  := -(2 ** (DATA_WIDTH - 1));     -- -128
    -- Accumulator: K=49, max |acc with bias| = 16256 + 49*127² = 806025 → 20-bit
    constant ACC_W       : positive := 24;

    -- -------------------------------------------------------------------------
    -- Types
    -- -------------------------------------------------------------------------
    type pixel_buf_t is array (0 to N_PX - 1)   of std_logic_vector(DATA_WIDTH - 1 downto 0);
    type acc_buf_t   is array (0 to D_MODEL - 1) of signed(ACC_W - 1 downto 0);
    type pe_row_t    is array (0 to D_MODEL - 1) of signed(DATA_WIDTH - 1 downto 0);

    -- -------------------------------------------------------------------------
    -- Weight ROMs (distributed / LUTRAM, async read)
    -- -------------------------------------------------------------------------
    signal pw_rom : patch_proj_w_rom_t := PATCH_PROJ_W_ROM;
    signal pb_rom : patch_proj_b_rom_t := PATCH_PROJ_B_ROM;
    signal pe_rom : pos_embed_rom_t    := POS_EMBED_ROM;
    -- Vivado will use distributed RAM (LUT-RAM) because reads are combinational.
    attribute ram_style : string;
    attribute ram_style of pw_rom : signal is "distributed";
    attribute ram_style of pb_rom : signal is "distributed";
    attribute ram_style of pe_rom : signal is "distributed";

    -- -------------------------------------------------------------------------
    -- Pixel buffer  (FF array, async read, sync write)
    -- -------------------------------------------------------------------------
    signal pixel_buf : pixel_buf_t := (others => (others => '0'));

    -- -------------------------------------------------------------------------
    -- FSM
    -- -------------------------------------------------------------------------
    type state_t is (ST_IDLE, ST_COLLECT, ST_PROJECT, ST_OUTPUT, ST_DONE);
    signal state : state_t := ST_IDLE;

    signal px_cnt    : integer range 0 to N_PX    := 0;
    signal patch_cnt : integer range 0 to SEQ_LEN := 0;
    signal d_cnt     : integer range 0 to D_MODEL := 0;
    signal k_cnt     : integer range 0 to PATCH_PX := 0;
    signal out_cnt   : integer range 0 to D_MODEL := 0;

    -- Accumulator for current patch projection
    signal acc_buf   : acc_buf_t;
    -- Positional embedding row for current patch (latched at start of OUTPUT)
    signal pe_row    : pe_row_t;

    -- Projection sub-FSM phase within ST_PROJECT
    --   0 = init acc from bias
    --   1 = MAC loop
    --   2 = latch pe_row
    signal proj_phase : integer range 0 to 2 := 0;

    -- -------------------------------------------------------------------------
    -- Helpers
    -- -------------------------------------------------------------------------
    function sat8 (x : signed) return std_logic_vector is
    begin
        if x > to_signed(I8_MAX, x'length) then
            return std_logic_vector(to_signed(I8_MAX, DATA_WIDTH));
        elsif x < to_signed(I8_MIN, x'length) then
            return std_logic_vector(to_signed(I8_MIN, DATA_WIDTH));
        end if;
        return std_logic_vector(resize(x, DATA_WIDTH));
    end function;

    -- Raster pixel address for (patch p, inner index k)
    function pix_addr (p, k : integer) return integer is
        variable p_row, p_col, r, c : integer;
    begin
        p_row := p / PATCHES_SID;
        p_col := p mod PATCHES_SID;
        r     := k / PATCH_SIZE;
        c     := k mod PATCH_SIZE;
        return (p_row * PATCH_SIZE + r) * IMG_SIZE + (p_col * PATCH_SIZE + c);
    end function;

begin

    -- =========================================================================
    -- Pixel buffer: synchronous write, combinational read
    -- =========================================================================
    p_pixel_wr : process(clk) is
    begin
        if rising_edge(clk) then
            if state = ST_COLLECT and i_valid = '1' then
                pixel_buf(px_cnt) <= i_data;
            end if;
        end if;
    end process p_pixel_wr;

    -- =========================================================================
    -- Main FSM
    -- =========================================================================
    p_main : process(clk) is
        variable v_px   : signed(DATA_WIDTH - 1 downto 0);
        variable v_pw   : signed(DATA_WIDTH - 1 downto 0);
        variable v_pb   : signed(DATA_WIDTH - 1 downto 0);
        variable v_prod : signed(2 * DATA_WIDTH - 1 downto 0);
        variable v_proj : signed(DATA_WIDTH - 1 downto 0);
        variable v_sum  : signed(DATA_WIDTH downto 0);
    begin
        if rising_edge(clk) then
            if rstn = '0' then
                state      <= ST_IDLE;
                px_cnt     <= 0;
                patch_cnt  <= 0;
                d_cnt      <= 0;
                k_cnt      <= 0;
                out_cnt    <= 0;
                proj_phase <= 0;
                done       <= '0';
                o_valid    <= '0';
                o_last     <= '0';
                o_channel  <= 0;
            else
                done    <= '0';
                o_valid <= '0';
                o_last  <= '0';

                case state is

                    -- ---------------------------------------------------------
                    when ST_IDLE =>
                        px_cnt    <= 0;
                        patch_cnt <= 0;
                        if start = '1' then
                            state <= ST_COLLECT;
                        end if;

                    -- ---------------------------------------------------------
                    -- Receive 784 pixels
                    -- ---------------------------------------------------------
                    when ST_COLLECT =>
                        if i_valid = '1' then
                            if px_cnt = N_PX - 1 then
                                px_cnt     <= 0;
                                patch_cnt  <= 0;
                                d_cnt      <= 0;
                                k_cnt      <= 0;
                                proj_phase <= 0;
                                state      <= ST_PROJECT;
                            else
                                px_cnt <= px_cnt + 1;
                            end if;
                        end if;

                    -- ---------------------------------------------------------
                    -- Project one patch:
                    --   phase 0 : initialise acc_buf with bias (D_MODEL cycles)
                    --   phase 1 : MAC loop D_MODEL × PATCH_PX
                    --   phase 2 : latch pe_row for current patch (D_MODEL cycles)
                    -- Then transition to ST_OUTPUT.
                    -- ---------------------------------------------------------
                    when ST_PROJECT =>

                        case proj_phase is

                            -- Phase 0: load bias (all acc combinatorially accessible)
                            when 0 =>
                                v_pb := signed(pb_rom(d_cnt));
                                acc_buf(d_cnt) <=
                                    shift_left(resize(v_pb, ACC_W), DATA_WIDTH - 1);
                                if d_cnt = D_MODEL - 1 then
                                    d_cnt <= 0;
                                    k_cnt <= 0;
                                    proj_phase <= 1;
                                else
                                    d_cnt <= d_cnt + 1;
                                end if;

                            -- Phase 1: MAC loop
                            when 1 =>
                                v_px  := signed(pixel_buf(pix_addr(patch_cnt, k_cnt)));
                                v_pw  := signed(pw_rom(d_cnt * PATCH_PX + k_cnt));
                                v_prod := v_px * v_pw;
                                acc_buf(d_cnt) <=
                                    acc_buf(d_cnt) + resize(v_prod, ACC_W);

                                if k_cnt = PATCH_PX - 1 then
                                    k_cnt <= 0;
                                    if d_cnt = D_MODEL - 1 then
                                        d_cnt <= 0;
                                        proj_phase <= 2;
                                    else
                                        d_cnt <= d_cnt + 1;
                                    end if;
                                else
                                    k_cnt <= k_cnt + 1;
                                end if;

                            -- Phase 2: latch pos_embed row
                            when others =>
                                pe_row(d_cnt) <=
                                    signed(pe_rom(patch_cnt * D_MODEL + d_cnt));
                                if d_cnt = D_MODEL - 1 then
                                    out_cnt <= 0;
                                    state   <= ST_OUTPUT;
                                else
                                    d_cnt <= d_cnt + 1;
                                end if;

                        end case;

                    -- ---------------------------------------------------------
                    -- Stream D_MODEL outputs for current patch: proj + pos_embed
                    -- ---------------------------------------------------------
                    when ST_OUTPUT =>
                        -- Saturate shifted accumulator to int8
                        v_proj := resize(
                            shift_right(acc_buf(out_cnt), DATA_WIDTH - 1),
                            DATA_WIDTH);
                        if acc_buf(out_cnt) >
                                shift_left(to_signed(I8_MAX, ACC_W), DATA_WIDTH - 1) then
                            v_proj := to_signed(I8_MAX, DATA_WIDTH);
                        elsif acc_buf(out_cnt) <
                                shift_left(to_signed(I8_MIN, ACC_W), DATA_WIDTH - 1) then
                            v_proj := to_signed(I8_MIN, DATA_WIDTH);
                        end if;

                        -- Saturating add of positional embedding
                        v_sum   := resize(v_proj, DATA_WIDTH + 1)
                                 + resize(pe_row(out_cnt), DATA_WIDTH + 1);
                        o_data    <= sat8(v_sum);
                        o_valid   <= '1';
                        o_channel <= patch_cnt * D_MODEL + out_cnt;

                        if out_cnt = D_MODEL - 1 then
                            o_last    <= '1';
                            if patch_cnt = SEQ_LEN - 1 then
                                state     <= ST_DONE;
                            else
                                patch_cnt  <= patch_cnt + 1;
                                out_cnt    <= 0;
                                d_cnt      <= 0;
                                k_cnt      <= 0;
                                proj_phase <= 0;
                                state      <= ST_PROJECT;
                            end if;
                        else
                            out_cnt <= out_cnt + 1;
                        end if;

                    -- ---------------------------------------------------------
                    when ST_DONE =>
                        done  <= '1';
                        state <= ST_IDLE;

                end case;
            end if;
        end if;
    end process p_main;

end architecture rtl;
