-- ============================================================================
-- weight_mem.vhd  --  Distributed-ROM weight memories for MNIST ViT encoder
-- ============================================================================
-- All eight weight matrices are stored as distributed (LUT-RAM) ROMs whose
-- initial contents come from weights_pkg.vhd (auto-generated by export_qat).
--
-- IMPORTANT -- why distributed (not BRAM):
--   gemm_mm reads weight data in the SAME cycle it drives the address
--   (it uses b_data directly, not b_data registered one cycle later).
--   BRAM requires a registered-address read path (1-cycle latency), which
--   would cause every MAC to use the weight from the PREVIOUS cycle's address.
--   Distributed ROM has zero combinational latency: data is valid in the
--   same cycle the address is presented.
--
-- Resource estimate for MODEL_DIM=32, HIDDEN_DIM=64 (int8):
--   WQ,WK,WV,WO : 4 × 1024 B = 4 KB  → ~256 LUT-RAM
--   W1,W2       : 2 × 2048 B = 4 KB  → ~256 LUT-RAM
--   B1,B2       : 64 + 32 B  = 96 B  → ~  6 LUT-RAM
--   Total ≈ 518 LUT-RAM cells out of 20800 available on XC7A35T.
--
-- Read timing (0-latency, fully combinational):
--   Cycle N: rd_addr presented  → rd_data valid in the SAME cycle N.
--
-- To update weights: re-run  python mnist_poc.py export  then re-synthesise.
-- ============================================================================

library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;

use work.clog2_pkg.all;
use work.weights_pkg.all;

-- ----------------------------------------------------------------------------
-- weight_mem entity  (interface unchanged from previous version)
-- ----------------------------------------------------------------------------
entity weight_mem is
    generic (
        DATA_WIDTH : positive := 8;
        MODEL_DIM  : positive := 32;
        HIDDEN_DIM : positive := 64
    );
    port (
        clk : in std_logic;   -- retained for interface compatibility (unused internally)

        -- MHA weight read ports
        w_q_addr : in  std_logic_vector(clog2(MODEL_DIM * MODEL_DIM) - 1 downto 0);
        w_q_re   : in  std_logic;
        w_q_data : out std_logic_vector(DATA_WIDTH - 1 downto 0);

        w_k_addr : in  std_logic_vector(clog2(MODEL_DIM * MODEL_DIM) - 1 downto 0);
        w_k_re   : in  std_logic;
        w_k_data : out std_logic_vector(DATA_WIDTH - 1 downto 0);

        w_v_addr : in  std_logic_vector(clog2(MODEL_DIM * MODEL_DIM) - 1 downto 0);
        w_v_re   : in  std_logic;
        w_v_data : out std_logic_vector(DATA_WIDTH - 1 downto 0);

        w_o_addr : in  std_logic_vector(clog2(MODEL_DIM * MODEL_DIM) - 1 downto 0);
        w_o_re   : in  std_logic;
        w_o_data : out std_logic_vector(DATA_WIDTH - 1 downto 0);

        -- FFN weight & bias read ports
        w1_addr  : in  std_logic_vector(clog2(HIDDEN_DIM * MODEL_DIM) - 1 downto 0);
        w1_re    : in  std_logic;
        w1_rdata : out std_logic_vector(DATA_WIDTH - 1 downto 0);

        b1_addr  : in  std_logic_vector(clog2(HIDDEN_DIM) - 1 downto 0);
        b1_re    : in  std_logic;
        b1_rdata : out std_logic_vector(DATA_WIDTH - 1 downto 0);

        w2_addr  : in  std_logic_vector(clog2(MODEL_DIM * HIDDEN_DIM) - 1 downto 0);
        w2_re    : in  std_logic;
        w2_rdata : out std_logic_vector(DATA_WIDTH - 1 downto 0);

        b2_addr  : in  std_logic_vector(clog2(MODEL_DIM) - 1 downto 0);
        b2_re    : in  std_logic;
        b2_rdata : out std_logic_vector(DATA_WIDTH - 1 downto 0)
    );
end entity weight_mem;

architecture rtl of weight_mem is

    ---------------------------------------------------------------------------
    -- ROM signals initialised from weights_pkg constants.
    -- rom_style = "distributed" forces LUT-RAM (zero read latency).
    -- This is essential: gemm_mm reads a_data/b_data in the SAME cycle it
    -- drives the address, so there must be no pipeline register between
    -- address input and data output.
    ---------------------------------------------------------------------------
    constant wq_mem : wq_rom_t := WQ_ROM;
    constant wk_mem : wk_rom_t := WK_ROM;
    constant wv_mem : wv_rom_t := WV_ROM;
    constant wo_mem : wo_rom_t := WO_ROM;
    constant w1_mem : w1_rom_t := W1_ROM;
    constant b1_mem : b1_rom_t := B1_ROM;
    constant w2_mem : w2_rom_t := W2_ROM;
    constant b2_mem : b2_rom_t := B2_ROM;

    attribute rom_style : string;
    attribute rom_style of wq_mem : constant is "distributed";
    attribute rom_style of wk_mem : constant is "distributed";
    attribute rom_style of wv_mem : constant is "distributed";
    attribute rom_style of wo_mem : constant is "distributed";
    attribute rom_style of w1_mem : constant is "distributed";
    attribute rom_style of b1_mem : constant is "distributed";
    attribute rom_style of w2_mem : constant is "distributed";
    attribute rom_style of b2_mem : constant is "distributed";

begin

    ---------------------------------------------------------------------------
    -- Zero-latency combinational ROM reads.
    -- Data valid in the SAME cycle the address is presented (no register).
    ---------------------------------------------------------------------------
    w_q_data <= wq_mem(to_integer(unsigned(w_q_addr)));
    w_k_data <= wk_mem(to_integer(unsigned(w_k_addr)));
    w_v_data <= wv_mem(to_integer(unsigned(w_v_addr)));
    w_o_data <= wo_mem(to_integer(unsigned(w_o_addr)));
    w1_rdata <= w1_mem(to_integer(unsigned(w1_addr)));
    b1_rdata <= b1_mem(to_integer(unsigned(b1_addr)));
    w2_rdata <= w2_mem(to_integer(unsigned(w2_addr)));
    b2_rdata <= b2_mem(to_integer(unsigned(b2_addr)));

end architecture rtl;

-- ============================================================================
-- End of file weight_mem.vhd
-- ============================================================================
